# Generated by Django 4.2.1 on 2023-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("surname", models.CharField(max_length=64)),
                ("id_client", models.CharField(max_length=64, unique=True)),
                ("mail", models.EmailField(max_length=64, null=True)),
                ("phone", models.CharField(max_length=32, unique=True)),
                ("street", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("colour", models.CharField(max_length=64)),
                ("species", models.CharField(max_length=9)),
                ("chip", models.CharField(max_length=64, unique=True)),
                ("registration", models.DateField()),
                ("about_pet", models.TextField()),
                ("image", models.ImageField(upload_to="image/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
