# Generated by Django 4.2.1 on 2023-08-20 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application_text", models.TextField()),
                ("application_date", models.DateTimeField()),
                ("is_approved", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("colour", models.CharField(max_length=64)),
                ("species", models.CharField(max_length=9)),
                ("breed", models.CharField(max_length=32)),
                ("sex", models.CharField(max_length=9)),
                ("chip", models.CharField(max_length=64, unique=True)),
                ("registration", models.DateField()),
                ("about_pet", models.TextField()),
                ("image", models.ImageField(upload_to="image/")),
                ("available_to_adoption", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("services", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("animal", models.ManyToManyField(to="pet.animal")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Treatments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("treatment_name", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("notes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.animal"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("surname", models.CharField(max_length=64)),
                ("id_client", models.CharField(max_length=64, unique=True)),
                ("mail", models.EmailField(max_length=64, null=True)),
                ("phone", models.CharField(max_length=32, unique=True)),
                ("street", models.CharField(max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="People",
        ),
        migrations.DeleteModel(
            name="Pet",
        ),
        migrations.AddField(
            model_name="adoption",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pet.animal"
            ),
        ),
        migrations.AddField(
            model_name="adoption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
