
# Generated by Django 4.2.4 on 2023-08-26 07:12

# Generated by Django 4.2.4 on 2023-08-26 09:45


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adoptionstory",
            options={"verbose_name_plural": "Adoption Stories"},
        ),
    ]
