# Generated by Django 4.2.4 on 2023-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0002_adoption_animal_services_treatments_userprofile_and_more"),
        ("pet", "0002_remove_people_id_client_pet_available_for_adoption_and_more"),
    ]

    operations = []
