# Generated by Django 4.0.6 on 2023-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_merge_20230820_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_client',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='animap_pics/'),
        ),
    ]
