# Generated by Django 4.2.4 on 2023-08-26 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0003_animal_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="favorites",
            new_name="favourites",
        ),
    ]
