# Generated by Django 4.2.4 on 2023-08-26 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0004_alter_userprofile_profile_picture"),
        ("pet", "0004_rename_favorites_animal_favourites"),
    ]

    operations = []
