# Generated by Django 4.2.4 on 2023-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0006_alter_animal_favourites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("", "Select Status"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
