# Generated by Django 4.2.4 on 2023-08-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0007_alter_adoption_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pet.location",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default.jpg", null=True, upload_to="profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="favourites",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
