# Generated by Django 4.0.6 on 2023-08-20 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_adoption_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animal',
            name='registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
