# Generated by Django 4.0.6 on 2023-08-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_alter_adoption_application_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Treatments',
            new_name='Treatment',
        ),
    ]
