# Generated by Django 4.2.4 on 2023-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0011_remove_service_animal_service_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.ImageField(upload_to="animal_pics/"),
        ),
    ]
