# Generated by Django 4.2.4 on 2023-08-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0012_alter_animal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("", "Select Service"),
                    ("Luxury Spa Day", "Luxury Spa Day"),
                    ("Canine Massage Therapy", "Canine Massage Therapy"),
                    (
                        "Personalized Training Packages",
                        "Personalized Training Packages",
                    ),
                    ("Pet Photography and Portraits", "Pet Photography and Portraits"),
                    ("Pet Parties and Events", "Pet Parties and Events"),
                    ("VIP Boarding Suites", "VIP Boarding Suites"),
                    ("Pet Concierge Services", "Pet Concierge Services"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="notes",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="treatment_name",
            field=models.CharField(
                choices=[
                    ("", "Select Treatment"),
                    ("Vaccination", "Vaccination"),
                    ("Deworming", "Deworming"),
                    ("Flea and Tick Prevention", "Flea and Tick Prevention"),
                    ("Dental Care", "Dental Care"),
                    ("Annual Wellness Check-up", "Annual Wellness Check-up"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
