# Generated by Django 4.2.4 on 2023-08-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0013_alter_service_description_alter_service_service_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
