# Generated by Django 4.2.4 on 2023-08-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0014_alter_service_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("", "Select Status"),
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Denied", "Denied"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
