# Generated by Django 4.2.4 on 2023-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0015_adoption_application_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="colour",
            new_name="color",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="sex",
        ),
        migrations.AddField(
            model_name="animal",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("", "Select Size"), ("Male", "Male"), ("Female", "Female")],
                default="",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="location",
            field=models.CharField(
                choices=[
                    ("", "Select Size"),
                    ("Warsaw", "WAW"),
                    ("Krakow", "KRK"),
                    ("Wroclaw", "WRO"),
                    ("Poznan", "POZ"),
                    ("Lodz", "LDZ"),
                    ("Gdansk", "GDA"),
                    ("Szczecin", "SCZ"),
                    ("Bydgoszcz", "BGD"),
                    ("Katowice", "KAT"),
                    ("Gdynia", "GDY"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="size",
            field=models.CharField(
                choices=[
                    ("", "Select Size"),
                    ("Small", "Small (0-10kg)"),
                    ("Medium", "Medium (11-30kg)"),
                    ("Large", "Large (31-50kg)"),
                    ("Exter Large", "Extra Large (51kg or more)"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="application_text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="animal",
            name="about_pet",
            field=models.CharField(max_length=500),
        ),
    ]
