# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0016_rename_colour_animal_color_remove_animal_sex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                choices=[
                    ("", "Select Size"),
                    ("Warsaw", "WAW"),
                    ("Krakow", "KRK"),
                    ("Wroclaw", "WRO"),
                    ("Poznan", "POZ"),
                    ("Lodz", "LDZ"),
                    ("Gdansk", "GDA"),
                    ("Szczecin", "SCZ"),
                    ("Bydgoszcz", "BGD"),
                    ("Katowice", "KAT"),
                    ("Gdynia", "GDY"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
