# Generated by Django 4.2.4 on 2023-08-22 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0018_alter_animal_location_alter_userprofile_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="available_to_adoption",
            new_name="is_available_for_adoption",
        ),
    ]
