# Generated by Django 4.2.4 on 2023-08-22 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0019_rename_available_to_adoption_animal_is_available_for_adoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="street",
        ),
    ]
