# Generated by Django 4.2.4 on 2023-08-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0020_remove_userprofile_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="date",
            field=models.DateField(auto_now_add=True, default="2023-08-22"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatment",
            name="next_date",
            field=models.DateField(default="2023-08-22"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adoption",
            name="application_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="registration",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
