# Generated by Django 4.2.4 on 2023-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0021_service_date_treatment_next_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("", "Select Gender"), ("Male", "Male"), ("Female", "Female")],
                default="",
                max_length=9,
            ),
        ),
    ]
