# Generated by Django 4.2.4 on 2023-08-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0022_alter_animal_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=32),
        ),
    ]
