# Generated by Django 4.2.4 on 2023-08-24 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0023_alter_animal_gender"),
        ("pet", "0023_alter_userprofile_phone"),
    ]

    operations = []
