# Generated by Django 4.2.4 on 2023-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0024_merge_20230824_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="adopt",
            field=models.CharField(
                choices=[
                    ("", "Select Species"),
                    ("Dog", "Dog"),
                    ("Cat", "Cat"),
                    ("Other", "Other"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="adoption",
            name="city",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="adoption",
            name="ever_pet",
            field=models.CharField(
                choices=[("", "Select Status"), ("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="adoption",
            name="house_or_apartment",
            field=models.CharField(
                choices=[
                    ("", "Select Status"),
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="adoption",
            name="how_do_you_like_spend_time",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="adoption",
            name="m2",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="adoption",
            name="street",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="adoption",
            name="what_will_happen_to_the_pet",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="adoption",
            name="why_do_you_want_to_adopt",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.CharField(
                choices=[
                    ("", "Select Species"),
                    ("Dog", "Dog"),
                    ("Cat", "Cat"),
                    ("Other", "Other"),
                ],
                default="",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
