# Generated by Django 4.2.4 on 2023-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0025_adoption_adopt_adoption_city_adoption_ever_pet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adoption",
            old_name="ever_pet",
            new_name="initial_pet",
        ),
        migrations.RenameField(
            model_name="adoption",
            old_name="house_or_apartment",
            new_name="living_space",
        ),
        migrations.RenameField(
            model_name="adoption",
            old_name="how_do_you_like_spend_time",
            new_name="pet_fate",
        ),
        migrations.RenameField(
            model_name="adoption",
            old_name="what_will_happen_to_the_pet",
            new_name="reason_for_adoption",
        ),
        migrations.RenameField(
            model_name="adoption",
            old_name="m2",
            new_name="square_meters",
        ),
        migrations.RenameField(
            model_name="adoption",
            old_name="why_do_you_want_to_adopt",
            new_name="time_spending_habbit",
        ),
        migrations.RemoveField(
            model_name="adoption",
            name="adopt",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="registration",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="treatment",
            name="description",
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adoption",
            name="application_text",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="animal",
            name="about_pet",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
