<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-26 07:12
=======
# Generated by Django 4.2.4 on 2023-08-26 09:45
>>>>>>> d5c4da0e0c29a8c4d2328e1fe3809ed9b2f3c766

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adoptionstory",
            options={"verbose_name_plural": "Adoption Stories"},
        ),
    ]
